"""init card and price tables

Revision ID: 1b86441b8d55
Revises: 
Create Date: 2026-08-06 17:46:42.810624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b86441b8d55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokedex_number', sa.Integer(), nullable=False),
    sa.Column('name_ko', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('set_code', sa.String(length=32), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('rarity', sa.String(length=32), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_code', 'card_number', name='uq_card_set_number')
    )
    op.create_index(op.f('ix_card_pokedex_number'), 'card', ['pokedex_number'], unique=False)
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('condition', sa.Enum('NM', 'LP', 'MP', 'HP', 'DMG', name='raw_condition'), nullable=True),
    sa.Column('grader', sa.Enum('PSA', 'BGS', 'CGC', 'SGC', name='grader'), nullable=True),
    sa.Column('grade', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='KRW', nullable=False),
    sa.Column('is_outlier', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(condition IS NOT NULL AND grader IS NULL AND grade IS NULL) OR (condition IS NULL AND grader IS NOT NULL AND grade IS NOT NULL)', name='ck_listing_variant_exclusive'),
    sa.CheckConstraint('price > 0', name='ck_listing_price_positive'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_listing_source_external')
    )
    op.create_index(op.f('ix_listing_card_id'), 'listing', ['card_id'], unique=False)
    op.create_index('ix_listing_card_listed_at', 'listing', ['card_id', 'listed_at'], unique=False)
    op.create_table('price_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('NM', 'LP', 'MP', 'HP', 'DMG', name='raw_condition'), nullable=True),
    sa.Column('grader', sa.Enum('PSA', 'BGS', 'CGC', 'SGC', name='grader'), nullable=True),
    sa.Column('grade', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('raw_min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raw_max_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('median_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(condition IS NOT NULL AND grader IS NULL AND grade IS NULL) OR (condition IS NULL AND grader IS NOT NULL AND grade IS NOT NULL)', name='ck_snapshot_variant_exclusive'),
    sa.CheckConstraint('min_price <= max_price', name='ck_snapshot_min_le_max'),
    sa.CheckConstraint('sample_count > 0', name='ck_snapshot_sample_positive'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshot_card_date', 'price_snapshot', ['card_id', 'snapshot_date'], unique=False)
    op.create_index('ux_snapshot_variant_date', 'price_snapshot', ['card_id', 'condition', 'grader', 'grade', 'snapshot_date'], unique=True, postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_snapshot_variant_date', table_name='price_snapshot', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_snapshot_card_date', table_name='price_snapshot')
    op.drop_table('price_snapshot')
    op.drop_index('ix_listing_card_listed_at', table_name='listing')
    op.drop_index(op.f('ix_listing_card_id'), table_name='listing')
    op.drop_table('listing')
    op.drop_index(op.f('ix_card_pokedex_number'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
